### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by sotirisnik** [dxyang/DQN_pytorch#4]
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    main()
  File "main.py", line 117, in main
    atari_learn(env, task.env_id, num_timesteps=task.max_timesteps, double_dqn=double_dqn, dueling_dqn=dueling_dqn)
  File "main.py", line 72, in atari_learn
    dueling_dqn=dueling_dqn
  File "/home/sotirisnik/other/DQN_pytorch/learn.py", line 149, in dqn_learning
    obs, reward, done, info = env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/other/DQN_pytorch/utils/atari_wrappers.py", line 132, in _step
    obs, reward, done, info = self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/other/DQN_pytorch/utils/atari_wrappers.py", line 124, in _step
    obs, reward, done, info = self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 279, in _step
    return self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/other/DQN_pytorch/utils/atari_wrappers.py", line 93, in _step
    obs, reward, done, info = self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 279, in _step
    return self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/other/DQN_pytorch/utils/atari_wrappers.py", line 53, in _step
    obs, reward, done, info = self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/wrappers/monitoring.py", line 33, in _step
    observation, reward, done, info = self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 36, in _step
    observation, reward, done, info = self.env.step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/home/sotirisnik/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 73, in _step
    action = self._action_set[a]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
[2018-06-27 02:58:15,904] Finished writing results. You can upload them to the scoreboard via gym.upload('/home/sotirisnik/other/DQN_pytorch/tmp/BreakoutNoFrameskip-v4')

**Comment by cuiguangwu** [comment]
how to solve this problem?
