### ISSUE TITLE
How can I deal with it?

### ISSUE THREAD

**Issue by liyuxiang1111** [dxyang/DQN_pytorch#7]
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    main()
  File "main.py", line 132, in main
    atari_learn(env, task.env_id, num_timesteps=task.max_timesteps, double_dqn=double_dqn, dueling_dqn=dueling_dqn)
  File "main.py", line 79, in atari_learn
    dueling_dqn=dueling_dqn
  File "/home/liyuxiang/Documents/pytorch_DQN/learn.py", line 234, in dqn_learning
    q_s_a.backward(clipped_error.data.unsqueeze(1))
  File "/home/liyuxiang/.conda/envs/bim/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/liyuxiang/.conda/envs/bim/lib/python3.7/site-packages/torch/autograd/__init__.py", line 190, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "/home/liyuxiang/.conda/envs/bim/lib/python3.7/site-packages/torch/autograd/__init__.py", line 72, in _make_grads
    + str(out_shape) + ".")
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([32, 1]) and output[0] has a shape of torch.Size([32]).
[2024-11-15 06:21:57,472] Finished writing results. You can upload them to the scoreboard via gym.upload('/home/liyuxiang/Documents/pytorch_DQN/tmp/BreakoutNoFrameskip-v4')

**Comment by liyuxiang1111** [comment]
q_s_a.backward(clipped_error.data)
I change the backwards, but I don not know is right.
